#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SPEC="$PROJECT_DIR/scripts/spec"
OUT_FILE="$PROJECT_DIR/docs/COMMAND_INVENTORY.md"
MODE="${1:-write}"

TMP_FILE="$(mktemp -t spec_command_inventory_XXXXXX.md)"
trap 'rm -f "$TMP_FILE"' EXIT

HELP_TEXT="$("$SPEC" help)"

{
	echo "# Command Inventory"
	echo ""
	echo "> Generated from \`scripts/spec help\` by \`scripts/generate_command_inventory.sh\`."
	echo "> Do not edit this file manually."
	echo ""
	echo "| Command | Description |"
	echo "|---|---|"

	if echo "$HELP_TEXT" | grep -q "spec create"; then
		echo "| \`spec create\` | Alias for \`spec init\` |"
	fi

	echo "$HELP_TEXT" | awk '
		/^Commands:/ {in_commands=1; next}
		/^Options:/ {in_commands=0}
		in_commands {print}
	' | while IFS= read -r line; do
		trimmed="$(echo "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
		[[ -z "$trimmed" ]] && continue
		cmd="$(echo "$trimmed" | awk '{print $1}')"
		desc="$(echo "$trimmed" | sed -E 's/^[^[:space:]]+[[:space:]]+//')"
		[[ -z "$cmd" || "$cmd" == "Commands:" ]] && continue
		[[ "$cmd" == "spec" ]] && continue
		echo "| \`spec $cmd\` | $desc |"
	done
} | awk '!seen[$0]++' > "$TMP_FILE"

case "$MODE" in
	--check)
		if [[ ! -f "$OUT_FILE" ]]; then
			echo "Missing command inventory: $OUT_FILE" >&2
			exit 1
		fi
		diff -u "$OUT_FILE" "$TMP_FILE"
		;;
	--stdout)
		cat "$TMP_FILE"
		;;
	write|--write)
		cp "$TMP_FILE" "$OUT_FILE"
		echo "Updated: $OUT_FILE"
		;;
	*)
		echo "Usage: scripts/generate_command_inventory.sh [write|--check|--stdout]" >&2
		exit 1
		;;
esac
