complete -c spec -f
complete -c spec -a "init create init-interactive validate render export export-agent-context info list validate-all search status convert template watch diff export-eval ci doctor changelog graph version help"
complete -c spec -l format -d "Spec format" -a "yaml toml json agent dispatch markdown eval envelope mermaid dot"
complete -c spec -l payload-format -d "Envelope payload format" -a "agent dispatch"
complete -c spec -l output -d "Output path" -r
complete -c spec -l name -d "Spec name"
complete -c spec -l from -d "Import source"
complete -c spec -l to -d "Convert target format" -a "yaml toml json"
complete -c spec -l set -d "Status value" -a "draft ready in-progress review completed archived"
complete -c spec -l priority -d "Priority filter" -a "critical high medium low"
complete -c spec -l tag -d "Tag filter"
complete -c spec -l query -d "Search query"
complete -c spec -l max-depth -d "Directory scan depth"
complete -c spec -l dir -d "Directory"
complete -c spec -l max-files -d "Max files for ci"
complete -c spec -l jobs -d "Parallel ci workers"
complete -c spec -l quiet -d "Suppress output"
complete -c spec -l json -d "JSON output"
complete -c spec -l strict -d "Treat warnings as errors"
complete -c spec -l fail-fast -d "Stop ci on first failure"
complete -c spec -l unsafe-write -d "Allow writing outside project root"
complete -c spec -l strict-template-source -d "Restrict template lookup to project templates"
